services:
  spark-iceberg:
    build: spark/
    image: synthea-spark:latest
    container_name: spark-iceberg
    networks:
      - iceberg_net
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./spark:/home/iceberg/spark
      - ./data:/home/iceberg/data
      - ./spark/gx:/home/iceberg/gx
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - SPARK_WORKER_MEMORY=10g
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      - iceberg_net
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH__STYLE__ACCESS=true

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      - iceberg_net
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      - iceberg_net
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc anonymous set public minio/warehouse
      /usr/bin/mc mb minio/raw-landing;
      /usr/bin/mc anonymous set public minio/raw-landing
      tail -f /dev/null
      "

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - iceberg_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Airflow DB Initialization (Runs once and exits) ---
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: synthea-airflow:latest
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - iceberg_net
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: /bin/bash
    command:
      - -c
      - "airflow db migrate"
    restart: "no"

  # --- Airflow Webserver / API Server ---
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: synthea-airflow:latest
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - iceberg_net
    ports:
      - 8089:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__API__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__SIMPLE_AUTH_MANAGER__USERS=[{"username":"admin","password":"admin"}]
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__FERNET_KEY=fbZ1KVAs2A9vS8N9E4P7H2yT98v1bL2k_D3O8jE-7w4=
      - AIRFLOW_CONN_MINIO_CONN_ID=aws://admin:password@/?endpoint_url=http%3A%2F%2Fminio%3A9000
      - AIRFLOW__CORE__SECRET_KEY=airflow-secret-key-change-me
      - AIRFLOW__API_AUTH__JWT_SECRET=airflow-jwt-secret-change-me
      - PROJECT_ROOT=/home/amirbnsl/Projects/synthea

    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./tests:/opt/airflow/tests
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bin/:/opt/airflow/bin
      - ./config/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    user: "0:0"
    command: api-server

  # --- Airflow Scheduler (The Brain) ---
  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: synthea-airflow:latest
    container_name: airflow-dag-processor
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - iceberg_net
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__API__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__SIMPLE_AUTH_MANAGER__USERS=[{"username":"admin","password":"admin"}]
      - AIRFLOW__CORE__FERNET_KEY=fbZ1KVAs2A9vS8N9E4P7H2yT98v1bL2k_D3O8jE-7w4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SECRET_KEY=airflow-secret-key-change-me
      - AIRFLOW__API_AUTH__JWT_SECRET=airflow-jwt-secret-change-me
      - PROJECT_ROOT=/home/amirbnsl/Projects/synthea
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests
      - ./config/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    user: "0:0"
    command: dag-processor

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: synthea-airflow:latest
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - iceberg_net
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__API__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__SIMPLE_AUTH_MANAGER__USERS=[{"username":"admin","password":"admin"}]
      - AIRFLOW__CORE__FERNET_KEY=fbZ1KVAs2A9vS8N9E4P7H2yT98v1bL2k_D3O8jE-7w4=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_MINIO_CONN_ID=aws://admin:password@/?endpoint_url=http%3A%2F%2Fminio%3A9000
      - AIRFLOW__CORE__SECRET_KEY=airflow-secret-key-change-me
      - AIRFLOW__API_AUTH__JWT_SECRET=airflow-jwt-secret-change-me
      - PROJECT_ROOT=/home/amirbnsl/Projects/synthea
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./tests:/opt/airflow/tests
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bin/:/opt/airflow/bin
      - ./config/simple_auth_manager_passwords.json.generated:/opt/airflow/simple_auth_manager_passwords.json.generated
    user: "0:0"
    command: scheduler

volumes:
  postgres_data:

networks:
  iceberg_net:
