FROM apache/airflow:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre-headless && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN PIP_ROOT_USER_ACTION=ignore /home/airflow/.local/bin/pip install apache-airflow-providers-amazon psycopg2-binary asyncpg
USER airflow
